### PR TITLE
WIP Refactored the helm arguments to implement spaces

### PR DESCRIPTION
**Pull request by endzyme**
Some of the plugin ecosystems parse opts with bash and thus sometimes can get hung up on `-f=this.file` vs `-f this.file` -- with the error "Cannot find file: "=this.file".

The Popen module should handle all necessary escaping by default with anything passed into args so even setting `--set my_key=has spaces in value` should be handled correctly.

### CODE REVIEW

**Comment by endzyme** [comment]
@nirdothan if you wanted to test this out locally - that would be awesome (to assure it satisfies the needs for your `secrets` plugin workflow)

**Comment by nirdothan** [comment]
Will try next week

**Comment by nirdothan** [comment]
We tested the branch today with helm secrets. Works fine.

**Comment by endzyme** [comment]
Sounds great. I'll be running this locally for a week along with some others to see if there are any edge cases where this won't work. @nirdothan is it ok to release this on Friday?

**Comment by endzyme** [comment]
From using this for a while now and I think we're ok to start merging and releasing. Thanks again for the contribution and the patience @nirdothan

**Comment by nirdothan** [comment]
Thank you very much

**Comment by endzyme** [comment]
I'm merging this today. Our other code owner is away but I'm pushing forward with a final review later on. I've been running this for a week and I know Andy has been as well. I've also had some other confirmations on basic tests with the end-to-end tests as well as with other folks at ReactiveOps. 

I'll merge and cut a release shortly.

**Comment by endzyme** [comment]
Merging this outside of normal PR review - will revisit a retro review when the other code owner is back online :) :wave:

**Pull request merged**
